#stage 1
FROM node:latest as node
WORKDIR /web
COPY . .
RUN npm install
RUN npm run build 
#stage 2
FROM nginx:alpine
COPY --from=node /web/dist/ngx-admin /usr/share/nginx/html
RUN mkdir /usr/share/nginx/html/ImageStorage